import type { Metadata } from "next";
import { SITE } from "./site";

/**
 * The share card generated by app/opengraph-image.tsx, as an absolute URL.
 *
 * It has to be named here rather than left to the file convention: that
 * convention sets the image for ONE route segment, not for the segments below
 * it, and because buildMeta authors a complete `openGraph` object nothing
 * backfills an image on the child routes. Shipping it unset left 42 of 44
 * pages rendering as blank cards in every share.
 *
 * Naming it is safe on the homepage too — file-based metadata outranks the
 * metadata object, so `/` still serves the generated file and does not end up
 * with the tag twice.
 *
 * Next emits the image extensionless (out/opengraph-image), which is why nginx
 * forces image/png on it. Keep the URL extensionless to match.
 */
const OG_IMAGE = {
  url: `${SITE.url}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "Merrill Digital Systems — custom software and websites in Utah",
};

/**
 * Every route builds its metadata through this so canonicals, OG and Twitter
 * cards can never drift apart. Paths are extensionless — the .html canonicals
 * the pre-2026 site published are 301'd to these.
 *
 * Pass `ogImage` only when a route genuinely needs its own card, and `article`
 * on editorial routes so they advertise og:type=article with real dates
 * instead of claiming to be a generic website.
 */
export function buildMeta({
  title,
  description,
  path,
  ogImage,
  noIndex = false,
  article,
}: {
  title: string;
  description: string;
  path: string;
  ogImage?: string;
  noIndex?: boolean;
  article?: { publishedTime: string; modifiedTime?: string };
}): Metadata {
  const images = ogImage
    ? [{ url: ogImage, width: 1200, height: 630, alt: title }]
    : [OG_IMAGE];
  // Next resolves "/" against metadataBase without a trailing slash, which
  // would disagree with the sitemap. Pin the homepage to the absolute form.
  const canonical = path === "/" ? `${SITE.url}/` : path;

  const openGraph: Metadata["openGraph"] = article
    ? {
        type: "article",
        title,
        description,
        url: canonical,
        images,
        publishedTime: article.publishedTime,
        modifiedTime: article.modifiedTime ?? article.publishedTime,
        authors: [SITE.founder],
      }
    : { type: "website", title, description, url: canonical, images };

  return {
    // `absolute` opts out of the root layout's "%s | Merrill Digital Systems"
    // template. Callers pass a complete, SERP-length-checked title; without
    // this the brand appears twice and titles run past 80 characters.
    title: { absolute: title },
    description,
    alternates: { canonical },
    robots: noIndex ? { index: false, follow: false } : { index: true, follow: true },
    openGraph,
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [images[0].url],
    },
  };
}
