import type { MetadataRoute } from "next";
import { SITE } from "@/lib/site";

export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE.name,
    short_name: SITE.shortName,
    description:
      "Custom software and websites for businesses that have outgrown spreadsheets.",
    start_url: "/",
    display: "minimal-ui",
    background_color: "#f3f2f2",
    theme_color: "#f3f2f2",
    // Generated by app/icon.tsx, which emits an EXTENSIONLESS file (`out/icon`),
    // so the src has no .png — nginx sets the content type for this exact path.
    // The mark is a solid cobalt field, so it survives Android's maskable crop
    // without needing a separate padded variant.
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
